# Python Advance Assignment
## Assignment - 23 [ FSDS NOV 21 ]

### Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?
**Ans:**

Matplotlib provides a convenient method called subplots for increasing the comparison between different figures on the same graph. Subplots mean a group of smaller axes (where each axis is a plot) that can exist together within a single figure.

Also, A scatter chart shows the relationship between two different variables and it can reveal the distribution trends.

### Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?
**Ans:** 

Compound interest causes one's wealth to grow faster. It makes a sum of money grow at a faster rate than simple interest because one will earn returns on the money other invest, as well as on returns at the end of every compounding period. This means that one don't have to put away as much money to reach others goals.

### Q3. What is a histogram, exactly? Name a numpy method for creating such a graph ?
**Ans:**

A histogram displays numerical data by grouping data into "bins" of equal width. Each bin is plotted as a bar whose height corresponds to how many data points are in that bin. Bins are also sometimes called "intervals", "classes", or "buckets".

`NumPy.histogram()` Method in Python can be used.

Histogram shows total values of X wrt Y. Which means at any particular position of X, Y value shows the total number of counts or data below that value of X. `numpy.histogram()` is the built in function used. 

### Q4. If necessary, how do you change the aspect ratios between the X and Y axes ?
**Ans:** 

We can use `figure(figsize=(10,8))` function inside the `matplot.pyplot` library which we scale down or up the graph.

### Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays ?
**Ans:** 

- In `regular multiplication` values of same index get multiplied.
- In `dot product` there is row wise multiplication, row of one array with column of second array and so on.
- In `outer multiplication` every element of first array a1 will be multiply by every element of other array a2 such such the number of columns will be equal to the number of element in another array a2.

In [1]:
import numpy as np


# vector v1 of dimension (2, 2)
v1 = np.array([[1, 2], [1, 2]])

# vector v2 of dimension (2, 2)
v2 = np.array([[1, 2], [1, 2]])

print("vector multiplication")
print(np.dot(v1, v2))
print("outer multiplication")
print(np.outer(v1, v2))
print("\nElementwise multiplication of two vector")
print(v1 * v2)



vector multiplication
[[3 6]
 [3 6]]
outer multiplication
[[1 2 1 2]
 [2 4 2 4]
 [1 2 1 2]
 [2 4 2 4]]

Elementwise multiplication of two vector
[[1 4]
 [1 4]]


### Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment ?
**Ans:**

`np.pmt(rate, nper, pv)` function we will be using in order to calculate monthly mortgage payment before you purchase a house.
- `rate` = The periodic interest rate
- `nper` = The number of payment periods
- `pv` = The total value of the mortgage loan

### Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data ?
**Ans:** 

Yes, an array can store the string. The limitation which imposed on the string data is, whenever we store the data of string dtype then it should should keep in mind that the string which is having the maximum length is the limit. 

In [2]:
# importing the numpy library as np
import numpy as np

# Create a numpy array
# set the dtype to object
country = np.array(['USA', 'Japan', 'UK', '', 'India', 'China'], dtype = 'object')

# Print the array
print(country)

['USA' 'Japan' 'UK' '' 'India' 'China']


In [3]:
#Now we can use assign a value of arbitrary length at the place of missing value in the given array.

# Assign 'New Zealand' to the missing value
country[country == ''] = 'New Zealand'
  
# Print the array
print(country)

['USA' 'Japan' 'UK' 'New Zealand' 'India' 'China']
