# Python Advance Assignment
## Assignment - 22 [ FSDS NOV 21 ]

### Q1. What are the benefits of the built-in array package, if any?
**Ans:** 

The Array is much more rigid. That is, the items that an array contains must be of the same type. Therefore, the size of the item will also be the same. We can check the size of each item.



### Q2. What are some of the array package's limitations ?
**Ans:**  

The number of elements to be stored in an array should be known in advance. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.

Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.

Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem

### Q3. Describe the main differences between the array and numpy packages ?
**Ans:**  

The array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations.

An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.

In case of array we do not form a tabular structure, while in numpy it forms a tabular structure 

### Q4. Explain the distinctions between the empty, ones, and zeros functions ?
**Ans:** 

The distinctions between the `empty`, `ones`, and `zero` functions are as follows :  
- `Empty function:` An empty function is a function that does not contain any statement within its body. If you try to write a function definition without any statement in python ,it will return an error. To avoid this, we use pass statement. pass is a special statement in Python that does nothing. It only works as a dummy statement.  
- `Ones:` This function returns a new array of given shape and data type, where the element’s value is 1.  
- `Zeros:` This function returns a new array of given shape and data type, where the element’s value is 0.  

### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument ?
**Ans:**  

`fromfunction()` function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z). Parameters : function : [callable] The function is called with N parameters, where N is the rank of shape.



### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression `A + n` ?
**Ans:** 

If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that value in it. 

In [1]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr + 1)

[2 3 4 5 6]


### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome ?
**Ans:**

No, it won't.

In [2]:
#using scalar operations gives an error
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
a = arr += 1
print(a)

SyntaxError: invalid syntax (3130113566.py, line 5)

### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays ?
**Ans:** 

Yes, it is possible that we can include a string of fixed length in numpy array. 

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. if longer strings is allocateed it might cause a computation problem basically increse the time complexity.

### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays ?
**Ans:**

NumPy's concatenate function can be used to concatenate two arrays either row-wise or column-wise. Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0. The resulting array after row-wise concatenation is of the shape 6 x 3, i.e. 6 rows and 3 columns.

In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = arr1+arr2
arr1 = arr1*arr2

print(arr)
print("\n",arr1)

[[ 6  8]
 [10 12]]

 [[ 5 12]
 [21 32]]


### Q10. What is the best way to use a Boolean array to mask another array ?
**Ans:** 

The best way to use a Boolean array to mask another array is by Using `masked_where` of numpy package

Boolean masking is typically the most efficient way to quantify a sub-collection in a collection. Masking in python and data science is when you want manipulated data in a collection based on some criteria. The criteria you use is typically of a true or false nature, hence the boolean part.

Using `masked_where()` function: Pass the two array in the function as a parameter then use numpy. ma. masked_where() function in which pass the condition for masking and array to be masked. 

Using `masked_where()`, `getmask()` and `masked_array()` function: Pass the two array in the function as a parameter then use numpy. ma.

### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute ?
**Ans:** 

`np.std` and math package can be used individually. one method is shown below standar then we can use pandas or using srpiting line by line to ding standard deviation.
using pandas std() is generally nicer way and faster.

In [4]:
import math
def variance(data, ddof=0):
  n = len(data)
  mean = sum(data) / n
  return sum((x - mean) ** 2 for x in data) / (n - ddof)


def stdev(data):
  var = variance(data)
  std_dev = math.sqrt(var)
  return std_dev

stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])



2.4

### 12. What is the dimensionality of a Boolean mask-generated array ?
**Ans:**

It will have same dimensionality as input array.