# Python Programming Basic Assignment
## Assignment - 08 [ FSDS NOV 21 ]

### 1. Write a Python Program to Add two Matrices ?

In [1]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,8]])
mat2 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 8]]  and 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  is 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 17]] 


### 2. Write a Python Program to Multiply two Matrices ?

In [2]:
# Take 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

for r in result:
    print(r)



[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


### 3. Write a Python Program to transpose a Matrix ?

In [3]:
import numpy 
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,8]])
print(mat1)
print("\n")
print("Tnasposed matrix",numpy.transpose(mat1))

[[1 2 3]
 [4 5 6]
 [7 8 8]]


Tnasposed matrix [[1 4 7]
 [2 5 8]
 [3 6 8]]


### 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [5]:
try:
    sentance = input("Enter the words: ")
    words = [word.lower() for word in sentance.split()]
    words.sort()
    
    print("Sorted order of words:")
    for word in words:
        print(word, end = ' ')
    
except Exception as e:
    print(e)

Enter the words: This is task from the Assignment
Sorted order of words:
assignment from is task the this 

### 5. Write a Python Program to remove Punctuations From a String ?

In [6]:
punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''  
b ='hi!, how are you ?' 
no_punct = ""  
for char in b:  
   if char not in punctuation:  
       no_punct = no_punct + char    
print(no_punct)  

hi how are you 
